version: "3.9"

services:
  application:
    container_name: "acer-app"
    build:
      context: ./docker/application
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./src:/php"

  mysql:
    container_name: "acer-mysql"
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"

  redis:
    container_name: "acer-redis"
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    ports:
      - "6379:6379"
